/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.11 and Signal Processing Toolbox 8.7.
 * Generated on: 05-Jun-2024 20:43:37
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 38
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "arm_math.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2021b\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int FIRCoefsL = 38;
const float32_t FIRCoefs[38] = {
  -0.000994010712,-0.003726856317, -0.00683330372,-0.005889800377,  0.00278176344,
    0.01565851085,  0.02116228826,  0.01004153863, -0.01094297785, -0.01976978406,
  -0.001036997302,  0.03070757538,  0.03705205396,-0.003907766659, -0.06059604511,
   -0.06137435511,  0.04059889913,   0.2095426023,   0.3400955498,   0.3400955498,
     0.2095426023,  0.04059889913, -0.06137435511, -0.06059604511,-0.003907766659,
    0.03705205396,  0.03070757538,-0.001036997302, -0.01976978406, -0.01094297785,
    0.01004153863,  0.02116228826,  0.01565851085,  0.00278176344,-0.005889800377,
   -0.00683330372,-0.003726856317,-0.000994010712
};
